# install Elasticsearch by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: set cluster.name
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#cluster.name: my-application'
    line: 'cluster.name: {{elasticsearch_clurname}}'
    
#elasticsearch
- name: set auto_create_index
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    create: yes
    line: 'action.auto_create_index: {{elasticsearch_create_index}}'

- name: Restart elasticsearch
  service:
    name: elasticsearch.service
    state: started
    enabled: yes

# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sf /var/log/elasticsearch  /data/log/
    ln -sf /var/lib/elasticsearch /data/
    ln -sf /etc/elasticsearch/elasticsearch.yml /data/config/

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check Elasticsearch Version
    shell: sudo echo "elasticsearch  version:" $(curl -XGET localhost:9200  |grep number |cut -d '"' -f 4)  |sudo tee -a /data/logs/install_version.txt

# check service state
- name: Check Elasticsearch Service
  shell: systemctl status elasticsearch | grep Active*
  register: check_elasticsearch_service
  notify: check_elasticsearch_service
